apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kyverno
  namespace: kyverno
  annotations:
    apps.open-cluster-management.io/deployables: ''
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kyverno