apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: kyverno
  namespace: kyverno-channel
spec:
  pathname: https://kyverno.github.io/kyverno
  type: HelmRepo