apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: kyverno-placement-1
  namespace: kyverno
  labels:
    app: kyverno
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: install-kyverno, operator: In, values: ["true"]}