apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: kyverno-subscription-1
  namespace: kyverno
  annotations: {}
  labels:
    app: kyverno
    app.kubernetes.io/part-of: kyverno
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  name: kyverno
  channel: kyverno-channel/kyverno
  packageOverrides:
    - packageAlias: kyverno
      packageName: kyverno
      packageOverrides:
      - path: spec
        #  Run `helm show values kyverno/kyverno` to see available options for this chart
        value:
            replicaCount: 3 # High Availability
            extraArgs:
              - '--clientRateLimitQPS=20'
              - '--clientRateLimitBurst=50'
            resources:
              limits:
                memory: 2Gi
            initResources:
              limits:
                memory: 512Mi
            livenessProbe:
              initialDelaySeconds: 45
              periodSeconds: 40
            readinessProbe:
              initialDelaySeconds: 35
              periodSeconds: 20
            securityContext: null
  placement:
    placementRef:
      name: kyverno-placement-1
      kind: PlacementRule